structure(list(url = "https://api.shutterstock.com/v2/2bad%request400", 
    status_code = 400L, headers = structure(list(date = "Tue, 11 Dec 2018 22:25:33 GMT", 
        `content-type` = "text/html", `content-length` = "344", 
        connection = "close", etag = "\"5b27c3b9-158\"", `x-frame-options` = "DENY", 
        `x-xss-protection` = "1", `x-content-type-options` = "nosniff", 
        `strict-transport-security` = "max-age=86400", `content-security-policy` = "frame-ancestors 'none'"), .Names = c("date", 
    "content-type", "content-length", "connection", "etag", "x-frame-options", 
    "x-xss-protection", "x-content-type-options", "strict-transport-security", 
    "content-security-policy"), class = c("insensitive", "list"
    )), all_headers = list(structure(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 11 Dec 2018 22:25:33 GMT", 
            `content-type` = "text/html", `content-length` = "344", 
            connection = "close", etag = "\"5b27c3b9-158\"", 
            `x-frame-options` = "DENY", `x-xss-protection` = "1", 
            `x-content-type-options` = "nosniff", `strict-transport-security` = "max-age=86400", 
            `content-security-policy` = "frame-ancestors 'none'"), .Names = c("date", 
        "content-type", "content-length", "connection", "etag", 
        "x-frame-options", "x-xss-protection", "x-content-type-options", 
        "strict-transport-security", "content-security-policy"
        ), class = c("insensitive", "list"))), .Names = c("status", 
    "version", "headers"))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), .Names = c("domain", 
    "flag", "path", "secure", "expiration", "name", "value"), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<!DOCTYPE html>\n<html>\n<head>\n<title>Error</title>\n<style>\n    body {\n        width: 35em;\n        margin: 0 auto;\n        font-family: Tahoma, Verdana, Arial, sans-serif;\n    }\n</style>\n</head>\n<body>\n<h1>An error occurred.</h1>\n<p>Sorry, the page you are looking for is currently unavailable.<br/>\nPlease try again later.</p>\n</body>\n</html>\n"), 
    date = structure(1544567133, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = structure(c(0, 2.9e-05, 3.1e-05, 
    8e-05, 0.02529, 0.025355), .Names = c("redirect", "namelookup", 
    "connect", "pretransfer", "starttransfer", "total"))), .Names = c("url", 
"status_code", "headers", "all_headers", "cookies", "content", 
"date", "times"), class = "response")
