structure(list(url = "https://api.shutterstock.com/v2/images/recommendations", 
    status_code = 401L, headers = structure(list(date = "Tue, 11 Dec 2018 22:25:33 GMT", 
        `content-type` = "application/json; charset=utf8", `content-length` = "34", 
        connection = "keep-alive"), .Names = c("date", "content-type", 
    "content-length", "connection"), class = c("insensitive", 
    "list")), all_headers = list(structure(list(status = 401L, 
        version = "HTTP/1.1", headers = structure(list(date = "Tue, 11 Dec 2018 22:25:33 GMT", 
            `content-type` = "application/json; charset=utf8", 
            `content-length` = "34", connection = "keep-alive"), .Names = c("date", 
        "content-type", "content-length", "connection"), class = c("insensitive", 
        "list"))), .Names = c("status", "version", "headers"))), 
    cookies = structure(list(domain = logical(0), flag = logical(0), 
        path = logical(0), secure = logical(0), expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), .Names = c("domain", 
    "flag", "path", "secure", "expiration", "name", "value"), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"message\":\"Invalid access token\"}"), 
    date = structure(1544567133, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = structure(c(0, 2.8e-05, 0.024928, 
    0.054313, 0.142851, 0.142883), .Names = c("redirect", "namelookup", 
    "connect", "pretransfer", "starttransfer", "total"))), .Names = c("url", 
"status_code", "headers", "all_headers", "cookies", "content", 
"date", "times"), class = "response")
